server {
    listen 80;
    server_name daniela.nasrulfahmi.my.id;

    # Meningkatkan ukuran max body jika ada fitur upload file
    client_max_body_size 50M;

    # Gunakan resolver bawaan Docker agar Nginx tidak crash jika container api telat menyala
    resolver 127.0.0.11 valid=30s;

    location / {
        # Gunakan variabel agar Nginx meresolve IP saat runtime, bukan saat startup
        set $upstream http://backend-api:8000;
        proxy_pass $upstream;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
